### ISSUE TITLE
Margin/padding logical properties cannot be prefixed correctly

### ISSUE THREAD

**Issue by Andarist** [kitten/tiny-css-prefixer#5]
Those are not valid and thus the current script cannot prefix those correctly. 
https://github.com/kitten/tiny-css-prefixer/blob/aa8aa678aa9bd2d57ede91ff11c92d74a131869a/scripts/generate-prefix-map.js#L52-L55

Standard properties are called differently:
- padding-inline-start & padding-inline-end
- margin-inline-start & margin-inline-end

So a simple prefix appending cant work on those because of their prefixed counterparts not having `-inline` at all in them.

**Comment by kitten** [comment]
So, funny thing, they do exist and can simply be prefixed when we use `margin-start`, but yes, they're indeed not standard.
- https://developer.mozilla.org/en-US/docs/Web/CSS/WebKit_Extensions
- https://mdn.beonex.com/en/CSS/-moz-margin-start.html

The standard ones I haven't added support for because they wouldn't work in IE11 anyway afaik, so I haven't actually made any effort to add support for `{padding,margin}-inline-{start,end}` https://github.com/kitten/tiny-css-prefixer/blob/master/SUPPORT.md

> Intrinsic & Extrinsic Sizing: This is not widely supported yet, with IE11 and Edge not supporting it, and most other browsers requiring prefixes.

Even more so, the browsers that do support logical margin/padding properties, don't need any prefixing in the most commonly, up-to-date versions of themselves.

**Comment by Andarist** [comment]
Ok, I understand your goals here - but that would IMHO mean that you should drop `margin-start`-likes entirely. The goal of a prefixer is to prefix **valid** properties - outputting prefixed (legacy~) and valid declaration list. In this case, `margin-start` is not valid at all - as far as I can tell (I've looked through the web and tested it myself in real browsers), it's only the prefixed declaration that has a chance to work. What I mean - no one is going to write `margin-start: 1px;` so it could be handled by this prefixer.

**Comment by kitten** [comment]
That’s an excellent point! I’ll remove these properties then 👍

**Comment by kitten** [comment]
Just removed them, I'll see whether I'll push them out with a future release depending on what else may come up :) https://github.com/kitten/tiny-css-prefixer/commit/5015f93e9de78a6fd424299eec3f7ff762d51d29
